import RPi.GPIO as GPIO
import time

def main():
    GPIO.setmode(GPIO.BCM)
    GPIO.setwarnings(False)
    a = 6
    b = 13
    c = 19
    d = 26
    e = 16
    f = 20
    g = 21
    GPIO.setup(a, GPIO.OUT)
    GPIO.setup(b, GPIO.OUT)
    GPIO.setup(c, GPIO.OUT)
    GPIO.setup(d, GPIO.OUT)
    GPIO.setup(e, GPIO.OUT)
    GPIO.setup(f, GPIO.OUT)
    GPIO.setup(g, GPIO.OUT)
    # 0
    GPIO.output(a, 1)
    GPIO.output(b, 1)
    GPIO.output(c, 1)
    GPIO.output(d, 1)
    GPIO.output(e, 1)
    GPIO.output(f, 1)
    GPIO.output(g, 0)
    time.sleep(1)
    # 1
    GPIO.output(a, 0)
    GPIO.output(b, 1)
    GPIO.output(c, 1)
    GPIO.output(d, 0)
    GPIO.output(e, 0)
    GPIO.output(f, 0)
    GPIO.output(g, 0)
    time.sleep(1)
    # 2
    GPIO.output(a, 1)
    GPIO.output(b, 1)
    GPIO.output(c, 0)
    GPIO.output(d, 1)
    GPIO.output(e, 1)
    GPIO.output(f, 0)
    GPIO.output(g, 1)
    time.sleep(1)
    # 3
    GPIO.output(a, 1)
    GPIO.output(b, 1)
    GPIO.output(c, 1)
    GPIO.output(d, 1)
    GPIO.output(e, 0)
    GPIO.output(f, 0)
    GPIO.output(g, 1)
    time.sleep(1)
    # 4
    GPIO.output(a, 0)
    GPIO.output(b, 1)
    GPIO.output(c, 1)
    GPIO.output(d, 0)
    GPIO.output(e, 0)
    GPIO.output(f, 1)
    GPIO.output(g, 1)
    time.sleep(1)
    # 5
    GPIO.output(a, 1)
    GPIO.output(b, 0)
    GPIO.output(c, 1)
    GPIO.output(d, 1)
    GPIO.output(e, 0)
    GPIO.output(f, 1)
    GPIO.output(g, 1)
    time.sleep(1)
    # 6
    GPIO.output(a, 1)
    GPIO.output(b, 0)
    GPIO.output(c, 1)
    GPIO.output(d, 1)
    GPIO.output(e, 1)
    GPIO.output(f, 1)
    GPIO.output(g, 1)
    time.sleep(1)
    # 7
    GPIO.output(a, 1)
    GPIO.output(b, 1)
    GPIO.output(c, 1)
    GPIO.output(d, 0)
    GPIO.output(e, 0)
    GPIO.output(f, 0)
    GPIO.output(g, 1)
    time.sleep(1)
    # 8
    GPIO.output(a, 1)
    GPIO.output(b, 1)
    GPIO.output(c, 1)
    GPIO.output(d, 1)
    GPIO.output(e, 1)
    GPIO.output(f, 1)
    GPIO.output(g, 1)
    time.sleep(1)
    # 9
    GPIO.output(a, 1)
    GPIO.output(b, 1)
    GPIO.output(c, 1)
    GPIO.output(d, 1)
    GPIO.output(e, 0)
    GPIO.output(f, 1)
    GPIO.output(g, 1)
    time.sleep(1)
    # A
    GPIO.output(a, 1)
    GPIO.output(b, 1)
    GPIO.output(c, 1)
    GPIO.output(d, 0)
    GPIO.output(e, 1)
    GPIO.output(f, 1)
    GPIO.output(g, 1)
    time.sleep(1)
    # b
    GPIO.output(a, 0)
    GPIO.output(b, 0)
    GPIO.output(c, 1)
    GPIO.output(d, 1)
    GPIO.output(e, 1)
    GPIO.output(f, 1)
    GPIO.output(g, 1)
    time.sleep(1)
    # c
    GPIO.output(a, 0)
    GPIO.output(b, 0)
    GPIO.output(c, 0)
    GPIO.output(d, 1)
    GPIO.output(e, 1)
    GPIO.output(f, 0)
    GPIO.output(g, 1)
    time.sleep(1)
    # d
    GPIO.output(a, 0)
    GPIO.output(b, 1)
    GPIO.output(c, 1)
    GPIO.output(d, 1)
    GPIO.output(e, 1)
    GPIO.output(f, 0)
    GPIO.output(g, 1)
    time.sleep(1)
    # E
    GPIO.output(a, 1)
    GPIO.output(b, 0)
    GPIO.output(c, 0)
    GPIO.output(d, 1)
    GPIO.output(e, 1)
    GPIO.output(f, 1)
    GPIO.output(g, 1)
    time.sleep(1)
    # F
    GPIO.output(a, 1)
    GPIO.output(b, 0)
    GPIO.output(c, 0)
    GPIO.output(d, 0)
    GPIO.output(e, 1)
    GPIO.output(f, 1)
    GPIO.output(g, 1)
    time.sleep(1)
    GPIO.cleanup()

while True:
    main()

# video del funcioanmiento: https://youtu.be/9UZ14tmA-ic?si=G4li42H48jNURyrw
